import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
// import { addTwo } from '../../global'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  function add(a:number,b:number){
    return a+b;
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
            <h1>hello world</h1>
      </main>
    </>
  )
}

//install prisma in vs code
//npm install -D prisma
//npx prisma init scheme fil ?
//npm install @prisma/client
//lib >prismadb.ts
//npm install next-auth and bcrypt and @types/bcrypt
//then we export default NextAuth({providers:[Credentials({id:,name:,credentials:{email:{}}})]}) 
//async authorize(credentials) 
//what will u do if there is no credentials.email or password
// if u have email check if there exist a user with this email
//if password matches the one in record


